New-PSUScript -Name "ActiveDirectory-Connect.ps1" -Description "ActiveDirectory-Connect.ps1" -Path "ActiveDirectory-Connect.ps1" 
New-PSUScript -Name "ActiveDirectory-Connect.Tests.ps1" -Description "ActiveDirectory-Connect.Tests.ps1" -Path "ActiveDirectory-Connect.Tests.ps1" 
New-PSUScript -Name "HelloWorld.ps1" -Description "HelloWorld.ps1" -Path "HelloWorld.ps1" 
New-PSUScript -Name "LDAP-Connect.ps1" -Description "LDAP-Connect.ps1" -Path "LDAP-Connect.ps1" 
New-PSUScript -Environment "PowerShell 7" -Module "PowerShellUniversal.Apps.AutomatedLab" -Command "Start-Lab" 
New-PSUScript -Environment "PowerShell 7" -Module "PowerShellUniversal.Apps.AutomatedLab" -Command "Start-Lab" 
New-PSUScript -Environment "PowerShell 7" -Module "PowerShellUniversal.Apps.AutomatedLab" -Command "Start-Lab" 
New-PSUScript -Environment "PowerShell 7" -Module "PowerShellUniversal.Apps.AutomatedLab" -Command "Start-Lab" 
New-PSUScript -Environment "PowerShell 7" -Module "PowerShellUniversal.Apps.AutomatedLab" -Command "Start-Lab" 
New-PSUScript -Environment "PowerShell 7" -Module "PowerShellUniversal.Apps.AutomatedLab" -Command "Start-Lab" 
New-PSUScript -Environment "PowerShell 7" -Module "PowerShellUniversal.Apps.AutomatedLab" -Command "Start-Lab" 
New-PSUScript -Name "PSU-Lab.ps1" -Description "PSU-Lab.ps1" -Path "PSU-Lab.ps1" -Environment "Windows PowerShell 5.1" -Credential "Admin" 
New-PSUScript -Name "ReadSecret.ps1" -Description "ReadSecret.ps1" -Path "ReadSecret.ps1" 
New-PSUScript -Name "Test-Get-UDInactiveUsers.ps1" -Description "Test-Get-UDInactiveUsers.ps1" -Path "Test-Get-UDInactiveUsers.ps1"